# https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
